// Bakes the cribbage "29" track: samples 121 evenly-spaced stations (plus unit
// normals) along a hand-authored cubic-bezier path shaped like the digits 2 9,
// and writes them to app/games/cribbage.board.js as static data.
import { writeFileSync } from "node:fs";

// Continuous pen stroke: the 2, an underline bridge, up the 9's stem, around
// the bowl, ending curled inside it (hole 121 sits in the curl).
const START = [48, 78];
const SEGS = [
  [[44, 30], [150, 12], [158, 64]],    // top curl of the 2
  [[162, 108], [70, 146], [48, 210]],  // diagonal
  [[86, 224], [132, 224], [172, 216]], // base of the 2
  [[215, 208], [268, 224], [305, 232]],// bridge to the 9's tail
  [[330, 208], [338, 170], [340, 120]],// up the stem
  [[342, 64], [316, 36], [280, 34]],   // stem top to bowl top
  [[238, 36], [216, 68], [218, 102]],  // bowl left
  [[220, 138], [258, 158], [295, 150]],// bowl bottom
  [[316, 144], [324, 132], [318, 118]],// curl in — the game hole
];

const bez = (p0, [c1, c2, p1], t) => {
  const u = 1 - t;
  return [0, 1].map(
    (k) => u * u * u * p0[k] + 3 * u * u * t * c1[k] + 3 * u * t * t * c2[k] + t * t * t * p1[k],
  );
};

// dense polyline
const pts = [];
let prev = START;
for (const seg of SEGS) {
  for (let i = 1; i <= 400; i++) pts.push(bez(prev, seg, i / 400));
  prev = seg[2];
}
pts.unshift(START);
const cum = [0];
for (let i = 1; i < pts.length; i++) {
  cum.push(cum[i - 1] + Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]));
}
const total = cum[cum.length - 1];

function at(dist) {
  let lo = 0, hi = cum.length - 1;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (cum[mid] < dist) lo = mid + 1;
    else hi = mid;
  }
  const i = Math.max(1, lo);
  const t = (dist - cum[i - 1]) / (cum[i] - cum[i - 1] || 1);
  const p = [0, 1].map((k) => pts[i - 1][k] + t * (pts[i][k] - pts[i - 1][k]));
  const d = [pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]];
  const len = Math.hypot(d[0], d[1]) || 1;
  return { x: p[0], y: p[1], nx: -d[1] / len, ny: d[0] / len };
}

// 121 stations, hole 1 slightly in from the start, hole 121 at the end
const holes = [];
for (let h = 1; h <= 121; h++) {
  const dist = (h / 121) * (total - 6) + 3;
  const { x, y, nx, ny } = at(dist);
  holes.push({ x: +x.toFixed(1), y: +y.toFixed(1), nx: +nx.toFixed(3), ny: +ny.toFixed(3) });
}

const d =
  `M${START[0]} ${START[1]}` +
  SEGS.map(([c1, c2, p]) => `C${c1[0]} ${c1[1]} ${c2[0]} ${c2[1]} ${p[0]} ${p[1]}`).join("");

writeFileSync(
  new URL("../app/games/cribbage.board.js", import.meta.url),
  `// Generated by tools/bake-board.mjs — do not edit by hand.
// 121 stations along the "29" track with unit normals for lane offsets.
export const PATH = ${JSON.stringify(d)};
export const VIEW = [0, 0, 400, 260];
export const HOLES = ${JSON.stringify(holes)};
`,
);
console.log(`baked 121 holes, track length ${total.toFixed(0)}`);
